# Generated by Django 3.0.8 on 2020-09-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20200928_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='iso',
            old_name='name',
            new_name='iso',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='name',
            new_name='states',
        ),
    ]
